vim.api.nvim_create_user_command('MasonNullLsUpdate', function()
	require('mason-null-ls').check_install(true)
end, { force = true })
vim.api.nvim_create_user_command('MasonNullLsInstall', function()
	require('mason-null-ls').check_install(false)
end, { force = true })
